feat: 🎸 workpro issue template
wechaty/puppet-supports pull request #159
Opened 2022-12-25 17:38 UTC by hcfw007

2022-12-26 10:54 UTC, windmemory requested changes

2022-12-26 10:54 UTC, windmemory commented on .github/ISSUE_TEMPLATE/workpro_bug.md
> +title: '[FEAT]WorkPro:'
BUG?

2022-12-26 11:11 UTC, windmemory commented on .github/ISSUE_TEMPLATE/workpro_bug.md
> +title: '[Bug]WorkPro:'
To make sure this is consistent, we should use `BUG` instead of `Bug`, since the feature template is using `FEAT`.

2022-12-27 03:28 UTC, lijiarui approved these changes
Seems fantastic！

2022-12-27 03:28 UTC, merged